### ISSUE TITLE
Order references missing in Saferpay BO after update

### ISSUE THREAD

**Issue by fscheibler** [Invertus/saferpayofficial#161]
Hello,

After updating to version 1.2.1, we have noticed that order references (ABCDEFGHI) are no longer visible in the Saferpay back-office.

![image](https://github.com/Invertus/saferpayofficial/assets/131658355/c34f9c6d-759b-4abc-b180-07d70339b87a)

**Comment by justelis22** [comment]
Hi there @fscheibler,

Please make sure to use the latest 1.2.2 version, it has a lot of fixes that could also cover the one you have reported.

If that does not help, let me know and we will continue the investigation.

Best Regards,
Invertus Support team.

**Comment by fscheibler** [comment]
Hello @justelis22 

Thank you for your prompt response. I have updated to the latest version 1.2.2 as recommended. Unfortunately, the issue still persists.

Best regards,

Florent

**Comment by justelis22** [comment]
@fscheibler,

Can you please attach screenshots of the Saferpay module configuration? We will set up the module identically on our side and test this to see if the issue can be recreated.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hello @fscheibler,

I have analyzed the case and this is expected behavior. 
As I can see you are using the order creation rule "After authorization", which means the PrestaShop order is created only after the payment is authorized by Saferpay. 
The order reference at this moment (the order reference on Saferpay is the PrestaShop order number) does not exist yet.

You can use Transaction/Payment ID to match the order<->payment.

Best Regards,
Invertus Support team.
