### ISSUE TITLE
Automatisation

### ISSUE THREAD

**Issue by klemasson** [Invertus/saferpayofficial#32]
Bonjour,

Actuellement nous devons tout faire manuellement. 
C'est à dire comptabiliser le paiement dans le back office de saferpay et changer le statut de la commande dans le backoffice de prestashop.

Il y a t'il un moyen que tout cela se fasse de manière automatique ? C'est à dire que quand le client paie sa commande, le paiement est directement comptabiliser et que la commander passe en statut "en cours de préparation"

Merci et belle journée

**Comment by SimonasB88** [comment]
Hi @klemasson 
Thanks for raising the issue here again. Have you tried the latest module from this repository?

Also, could you check in module Settings, there is a dropdown menu, at the bottom of the settings in module, there you can set the automatic prime status when users create orders. Is it the case, that you are talking about?

Best Regards
Invertus Support Team

**Comment by klemasson** [comment]
Hello,

Thanks for your answer!
It seems to me that I have the last module. I have the v1.0.7. 

In fact, what I would like is that when a customer pays, in the back office of saferpay, the payment is automatically posted. Because we don't want to have to go and post every payment, it will take too much time. 

Yes, I did find the drop down menu, thank you! 

Have a nice day

**Comment by klemasson** [comment]
And the most annoying thing is that we don't receive the money on our account, although all the data are correct...

**Comment by SimonasB88** [comment]
@klemasson ok thanks for clarification.
We will try to help you on this one.

In order to investigate your issue and help you efficiently, can you send us access to your backoffice with its url and a FTP access to your store:

URL back office:
login back office:
password back office:

FTP host:
FTP login:
FTP password:
FTP port:

Due to privacy, send everything to support@invertus.eu.
Our team will check the issue.

Best Regards.
Invertus Support Team

**Comment by klemasson** [comment]
Hello,

It is sent!

Thanks for your help

**Comment by SimonasB88** [comment]
Hi @klemasson 

Could you clarify, if business licence was on “YES” during the payments and if at this point it works correctly?

![image](https://user-images.githubusercontent.com/29095235/126657202-39a8d049-5a9d-43f6-9236-ab21686f8dc2.png)

As for development side, successUrl contains businessLicense=1 and that should only come from this place. So could you do some real 1 cent payments in order to test? That would be the only option to test the payment transaction if there are no errors.

Best Regards
Invertus Support Team

**Comment by klemasson** [comment]
The problem is when I activate the buisness license, the payments do not work.  (photo attached)

But when I activate the business license, it works but I don't receive the money on our account.
<img width="837" alt="Capture d’écran 2021-07-22 à 16 53 31" src="https://user-images.githubusercontent.com/87759127/126660616-8baa8e42-e291-4449-a0ac-f70622539c18.png">

**Comment by SimonasB88** [comment]
Hello @klemasson 

We have discussed with our module developers and Six Payments company about this case.
It seems, that If business licence is disabled then everything should be working. We can see it is enabled, and thus licence error is received from Saferpay API, as it is seen in module error logs.

So we can state, that you are trying to use the Business licence, that is whether expired or is not correct. According to your Back Office module settings, your Business licence was enabled all the time, and you didn't try to disable Business licence and try making orders.

Best Regards,
Invertus Support Team

**Comment by klemasson** [comment]
Hello, 

I confess I don't understand. My problem is that we do not receive the payment on our account. 

The buisness license is well deactivated in our backoffice. 

I do not understand the link between the business license and the fact that we do not receive the money.

Where can I see the account number that is linked to our Saferpay account? To see if there is an error

<img width="1047" alt="Capture d’écran 2021-07-24 à 12 09 56" src="https://user-images.githubusercontent.com/87759127/126865381-5a772905-2ce1-4925-a27d-47021b56d372.png">

**Comment by Saimis777** [comment]
Hello @klemasson ,

Thank you for your reply, the fact that the payments do not arrive to your account can only lead to one thing, that some of the credentials in the fields are incorrect, if the credentials are correct, there should be no issues with receiving the money, as from our end we've checked the possible causes, and this is the only one that could be at the moment. The account that is linked should be the one that you create on Saferpay page, there you receive the credentials that you need to input to the module.

Let me know if you have any more questions!

--
Best regards,
Invertus Support team

**Comment by klemasson** [comment]
Hello,

Sorry for the delay in responding, I was on vacation. 
We were able to resolve our money problem on the account.  Thank you very much for your help. 
However, we would like it to be automatically accounted for.

Is it possible to do that?

Have a nice day!

**Comment by SimonasB88** [comment]
Hey @klemasson 

I have to double-check with the developer this, and come back to you, thank you for question.

Best Regards,
Invertus Support Team

**Comment by SimonasB88** [comment]
@klemasson 
we wanted to ask, what do you want to have accounted?

Best Regards,
Invertus Support Team

**Comment by klemasson** [comment]
I would like the payments in the backoffice (in attachment) to be counted automatically 

Because for the moment, I have to post them manually.

<img width="1030" alt="Capture d’écran 2021-08-13 à 14 46 33" src="https://user-images.githubusercontent.com/87759127/129359309-22271429-0abf-44a4-8aba-54a13dd21ef3.png">

**Comment by SimonasB88** [comment]
Dear @klemasson 

-- You just provided a picture for Saferpay dashboard, and we have no way of changing anything in there (It is your Six Payments/Saferpay account)

-- The payments that failed and were at “Awaiting saferpay …” were created only in Prestashop and not in Saferpay system and cannot be counted (Because of the business licence usage that was invalid). Those payments are invalid and should manually be changed to 'payment_error' or some different order state.

If we did not understand it correctly, please try to be more verbose about the issue at hand.

--
Best Regards
Invertus Support Team

**Comment by Saimis777** [comment]
Hello @klemasson ,

Could you clarify if you need further assistance please?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by klemasson** [comment]
Hello,

No, for the moment it's all good as is.

Thank you for your work

Kevin Lemasson
Rue du Grand Clos 101c
1913 Saillon

078 897 93 27
***@***.***
